### ISSUE TITLE
Fix <a> tag's href to redirect to correct URL

### ISSUE THREAD

**Issue by anujjoshi63** [anujjoshi63/smallurl#35]
Current Behavior:
After **Smallify**, on clicking the URL the link that opens is https://smallify.live/smallify.live/alias

Expected Behavior:
After **Smallify**, on clicking the URL the link that should open is https://smallify.live/alias

**Comment by Niranjan2048** [comment]
Pls assign this issue to me ,I can fix this!!

**Comment by anujjoshi63** [comment]
> Pls assign this issue to me ,I can fix this!!

Thanks! Assigned the issue to you.

**Comment by Niravprajapati1** [comment]
Can i work on this issue?

**Comment by Niranjan2048** [comment]
> I can fix this. Please assign it to me

Fixed it already

**Comment by anujjoshi63** [comment]
Hi @anshrusia200, Thanks but the issue was already assigned to someone else. You can still try fixing other issues
