### ISSUE TITLE
bug: The page does not load the example URL immediately on slower networks

### ISSUE THREAD

**Issue by anujjoshi63** [anujjoshi63/smallurl#39]
### Current behaviour: No URL before the Alias input (the second input box)

![193413813-596558bf-0e07-4c18-b4e0-270b091f8cfd](https://user-images.githubusercontent.com/14955086/193414108-9d13fe09-f8f1-4ace-a920-4ace8fcedce0.png)

### Expected behaviour: for now smallify.live URL should be seen.

![193413827-ab8cee93-1414-475b-88a6-eea863594592](https://user-images.githubusercontent.com/14955086/193414145-29c5a6d7-5f16-4304-92d3-723105a1fb68.png)

### Suggested fix
The url is dynamic and gets changed as soon as the js file loads. The react state is defaulted to "" instead of "smallify.live". Simply changing the default state to "smallify.live" should fix this issue.

**Comment by Rajkumar-justcoder** [comment]
Hey there,
is this fixed, if not then i would like to work on this

**Comment by anujjoshi63** [comment]
> Hey there, is this fixed, if not then i would like to work on this

Thanks @Rajkumar-justcoder! assigning it to you :)

**Comment by Rajkumar-justcoder** [comment]
would u mind if i use pnpm insted of npm or yarn 
lock files will not come on push

**Comment by anujjoshi63** [comment]
> would u mind if i use pnpm insted of npm or yarn lock files will not come on push

haha sure go ahead

**Comment by anujjoshi63** [comment]
Could you also remove the package-lock please?

**Comment by Rajkumar-justcoder** [comment]
yeah sure
