### ISSUE TITLE
[fix]: The "Copy Link" button does not include "https://"

### ISSUE THREAD

**Issue by anujjoshi63** [anujjoshi63/smallurl#46]
Expected behaviour:
After clicking on "Copy link" button, it should copy the URL but with "https://"

**Comment by Aamir-Ansari-almost** [comment]
I would like to fix this issue

**Comment by anujjoshi63** [comment]
@Aamir-Ansari-almost Assigning it to you :)

**Comment by Aamir-Ansari-almost** [comment]
Made the required changes, shall I open the pull request directly on main branch?

**Comment by anujjoshi63** [comment]
Yes sure go for it, create a PR for the `master` branch

**Comment by anujjoshi63** [comment]
@Aamir-Ansari-almost it seems you haven't created a PR yet. Are you still working on it and/or facing any difficulties?
