### ISSUE TITLE
[enhancement]: add description meta tag for / and /wa routes.

### ISSUE THREAD

**Issue by anujjoshi63** [anujjoshi63/smallurl#49]
The actual value of description can be the same as the value of `og:description`

**Comment by Shansince2k3** [comment]
@anujjoshi63 I would like to work on this.

**Comment by Amit3108** [comment]
I would like to fix this issue.

**Comment by anujjoshi63** [comment]
Thanks @Amit3108 assigning the issue to you.

**Comment by Amit3108** [comment]
I have added description meta tag and left a pull request. Please check it out
