### ISSUE TITLE
the web app is too simple for using Trpc

### ISSUE THREAD

**Issue by alizaenazet** [anujjoshi63/smallurl#65]
Trpc is great but we must understand the product requirement.
In this case should using nextjs API is enough for the requirement

**Comment by anujjoshi63** [comment]
I appreciate your feedback, but I think I have made the best decision for this project based on my understanding of the product. For me, this was a learning opportunity, and I can always say that **using tRPC IS THE product requirements**. I hope this message finds you well. Please refrain from creating another issue, as this matter is merely a difference in opinion and, in my view, does not require further attention. Thank you.
